version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - frontend
    restart: always  # Add this line to specify always restart

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always  # Add this line to specify always restart
